// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/go-version-watcher/pkg"
)

type GoDevClient struct {
	LatestStableStub        func(context.Context) (pkg.Version, error)
	latestStableMutex       sync.RWMutex
	latestStableArgsForCall []struct {
		arg1 context.Context
	}
	latestStableReturns struct {
		result1 pkg.Version
		result2 error
	}
	latestStableReturnsOnCall map[int]struct {
		result1 pkg.Version
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GoDevClient) LatestStable(arg1 context.Context) (pkg.Version, error) {
	fake.latestStableMutex.Lock()
	ret, specificReturn := fake.latestStableReturnsOnCall[len(fake.latestStableArgsForCall)]
	fake.latestStableArgsForCall = append(fake.latestStableArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.LatestStableStub
	fakeReturns := fake.latestStableReturns
	fake.recordInvocation("LatestStable", []interface{}{arg1})
	fake.latestStableMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GoDevClient) LatestStableCallCount() int {
	fake.latestStableMutex.RLock()
	defer fake.latestStableMutex.RUnlock()
	return len(fake.latestStableArgsForCall)
}

func (fake *GoDevClient) LatestStableCalls(stub func(context.Context) (pkg.Version, error)) {
	fake.latestStableMutex.Lock()
	defer fake.latestStableMutex.Unlock()
	fake.LatestStableStub = stub
}

func (fake *GoDevClient) LatestStableArgsForCall(i int) context.Context {
	fake.latestStableMutex.RLock()
	defer fake.latestStableMutex.RUnlock()
	argsForCall := fake.latestStableArgsForCall[i]
	return argsForCall.arg1
}

func (fake *GoDevClient) LatestStableReturns(result1 pkg.Version, result2 error) {
	fake.latestStableMutex.Lock()
	defer fake.latestStableMutex.Unlock()
	fake.LatestStableStub = nil
	fake.latestStableReturns = struct {
		result1 pkg.Version
		result2 error
	}{result1, result2}
}

func (fake *GoDevClient) LatestStableReturnsOnCall(i int, result1 pkg.Version, result2 error) {
	fake.latestStableMutex.Lock()
	defer fake.latestStableMutex.Unlock()
	fake.LatestStableStub = nil
	if fake.latestStableReturnsOnCall == nil {
		fake.latestStableReturnsOnCall = make(map[int]struct {
			result1 pkg.Version
			result2 error
		})
	}
	fake.latestStableReturnsOnCall[i] = struct {
		result1 pkg.Version
		result2 error
	}{result1, result2}
}

func (fake *GoDevClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GoDevClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GoDevClient = new(GoDevClient)
