// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/go-version-watcher/pkg"
)

type ImageChecker struct {
	ImageExistsStub        func(context.Context, pkg.Version) (bool, error)
	imageExistsMutex       sync.RWMutex
	imageExistsArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Version
	}
	imageExistsReturns struct {
		result1 bool
		result2 error
	}
	imageExistsReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ImageChecker) ImageExists(arg1 context.Context, arg2 pkg.Version) (bool, error) {
	fake.imageExistsMutex.Lock()
	ret, specificReturn := fake.imageExistsReturnsOnCall[len(fake.imageExistsArgsForCall)]
	fake.imageExistsArgsForCall = append(fake.imageExistsArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Version
	}{arg1, arg2})
	stub := fake.ImageExistsStub
	fakeReturns := fake.imageExistsReturns
	fake.recordInvocation("ImageExists", []interface{}{arg1, arg2})
	fake.imageExistsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ImageChecker) ImageExistsCallCount() int {
	fake.imageExistsMutex.RLock()
	defer fake.imageExistsMutex.RUnlock()
	return len(fake.imageExistsArgsForCall)
}

func (fake *ImageChecker) ImageExistsCalls(stub func(context.Context, pkg.Version) (bool, error)) {
	fake.imageExistsMutex.Lock()
	defer fake.imageExistsMutex.Unlock()
	fake.ImageExistsStub = stub
}

func (fake *ImageChecker) ImageExistsArgsForCall(i int) (context.Context, pkg.Version) {
	fake.imageExistsMutex.RLock()
	defer fake.imageExistsMutex.RUnlock()
	argsForCall := fake.imageExistsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ImageChecker) ImageExistsReturns(result1 bool, result2 error) {
	fake.imageExistsMutex.Lock()
	defer fake.imageExistsMutex.Unlock()
	fake.ImageExistsStub = nil
	fake.imageExistsReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *ImageChecker) ImageExistsReturnsOnCall(i int, result1 bool, result2 error) {
	fake.imageExistsMutex.Lock()
	defer fake.imageExistsMutex.Unlock()
	fake.ImageExistsStub = nil
	if fake.imageExistsReturnsOnCall == nil {
		fake.imageExistsReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.imageExistsReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *ImageChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ImageChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.ImageChecker = new(ImageChecker)
