// Code generated by counterfeiter. DO NOT EDIT.
// Copyright (c) 2026 Benjamin Borbe All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/go-version-watcher/pkg"
	"github.com/bborbe/notification/command/notification"
)

type NotificationPublisher struct {
	PublishNotificationStub        func(context.Context, notification.NotificationPublishCommand) bool
	publishNotificationMutex       sync.RWMutex
	publishNotificationArgsForCall []struct {
		arg1 context.Context
		arg2 notification.NotificationPublishCommand
	}
	publishNotificationReturns struct {
		result1 bool
	}
	publishNotificationReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NotificationPublisher) PublishNotification(arg1 context.Context, arg2 notification.NotificationPublishCommand) bool {
	fake.publishNotificationMutex.Lock()
	ret, specificReturn := fake.publishNotificationReturnsOnCall[len(fake.publishNotificationArgsForCall)]
	fake.publishNotificationArgsForCall = append(fake.publishNotificationArgsForCall, struct {
		arg1 context.Context
		arg2 notification.NotificationPublishCommand
	}{arg1, arg2})
	stub := fake.PublishNotificationStub
	fakeReturns := fake.publishNotificationReturns
	fake.recordInvocation("PublishNotification", []interface{}{arg1, arg2})
	fake.publishNotificationMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *NotificationPublisher) PublishNotificationCallCount() int {
	fake.publishNotificationMutex.RLock()
	defer fake.publishNotificationMutex.RUnlock()
	return len(fake.publishNotificationArgsForCall)
}

func (fake *NotificationPublisher) PublishNotificationCalls(stub func(context.Context, notification.NotificationPublishCommand) bool) {
	fake.publishNotificationMutex.Lock()
	defer fake.publishNotificationMutex.Unlock()
	fake.PublishNotificationStub = stub
}

func (fake *NotificationPublisher) PublishNotificationArgsForCall(i int) (context.Context, notification.NotificationPublishCommand) {
	fake.publishNotificationMutex.RLock()
	defer fake.publishNotificationMutex.RUnlock()
	argsForCall := fake.publishNotificationArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *NotificationPublisher) PublishNotificationReturns(result1 bool) {
	fake.publishNotificationMutex.Lock()
	defer fake.publishNotificationMutex.Unlock()
	fake.PublishNotificationStub = nil
	fake.publishNotificationReturns = struct {
		result1 bool
	}{result1}
}

func (fake *NotificationPublisher) PublishNotificationReturnsOnCall(i int, result1 bool) {
	fake.publishNotificationMutex.Lock()
	defer fake.publishNotificationMutex.Unlock()
	fake.PublishNotificationStub = nil
	if fake.publishNotificationReturnsOnCall == nil {
		fake.publishNotificationReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.publishNotificationReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *NotificationPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NotificationPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.NotificationPublisher = new(NotificationPublisher)
